using AElf.Sdk.CSharp;
using Google.Protobuf.WellKnownTypes;

namespace AElf.Contracts.HelloWorld
{
    // Contract class must inherit the class generated by the proto file
    public class HelloWorld : HelloWorldContainer.HelloWorldBase
    {
        // Method to update the message value. 
        public override Empty Update(StringValue input)
        {
            // Set the message value in the contract state
            State.Message.Value = input.Value;
            // Emit an event to notify listeners about the something happened during the execution of this method
            Context.Fire(new UpdatedMessage
            {
                Value = input.Value
            });
            // Return an empty response
            return new Empty();
        }

        public override Empty Initialize(Empty input)
        {
            Assert(!State.Initialized.Value, "already initialized");
            State.RandomNumberContract.Value =
                Context.GetContractAddressByName(SmartContractConstants.ConsensusContractSystemName);
            return new Empty();
        }

        // Method to read the current message value
        public override StringValue Read(Empty input)
        {
            // Retrieve the value from the state
            var value = State.Message.Value;
            // Return value retrieved
            return new StringValue
            {
                Value = value
            };
        }

        public override Character CreateCharacter(Empty input)
        {
            var existing = State.Characters[Context.Sender];
            Assert(existing == null, "already has a character");
            var randomBytes = State.RandomNumberContract.GetRandomBytes
                .Call(new Int64Value { Value = Context.CurrentHeight - 1 }.ToBytesValue()).Value.ToByteArray();
            var hash = HashHelper.ComputeFrom(Context.Sender).Value.ToByteArray();

            var character = new Character
            {
                Health = 60 + (randomBytes[0] ^ hash[0]) % 41, // Health is 60 ~ 100
                Strength = 40 + (randomBytes[1] ^ hash[1]) % 61, // Strength is 40 ~ 100
                Speed = 100 + (randomBytes[2] ^ hash[2]) % 101 // Strength is 100 ~ 200
            };
            State.Characters[Context.Sender] = character;
            return character;
        }

        public override Character GetMyCharacter(Empty input)
        {
            return State.Characters[Context.Sender] ?? new Character();
        }
    }
}